### PR TITLE
add site for documentation

### PR DESCRIPTION
**Pull request by pachadotdev**
hi @VKudlay !
I added a small site to read the documentation, which can be seen from vkudlay.github.io/gegravity if you merge this PR.
I shall keep my own fork, where I'll add lots of unit tests for this software, and of course I'll try to send another PR to contribute back.

### CODE REVIEW

**Comment by VKudlay** [comment]
Hey @pachadotdev ! Thanks so much! The website looks great and I think it would be awesome to make this available. I've checked over it and have let Tom know about this so he can at least check over before accepting. 

@tomzylkin Hey Tom. For some quick context, the website is a vignette browser implemented with [pkgdown](https://pkgdown.r-lib.org/).  Just wanted to loop you in before accepting, but it looks good to me!

**Review by VKudlay — APPROVED** [review]
Looks good to me!

**Comment by VKudlay** [comment]
@pachadotdev Update. Went ahead and set up the pages account

**Comment by pachadotdev** [comment]
I saw https://vkudlay.github.io/GEGravity/. Amazing!

**Pull request merged**
